// Code generated by "stringer -type=unfoldStateDetail"; DO NOT EDIT

package gotype

import "fmt"

const _unfoldStateDetail_name = "unfoldWaitStartunfoldWaitKeyunfoldWaitElem"

var _unfoldStateDetail_index = [...]uint8{0, 15, 28, 42}

func (i unfoldStateDetail) String() string {
	if i >= unfoldStateDetail(len(_unfoldStateDetail_index)-1) {
		return fmt.Sprintf("unfoldStateDetail(%d)", i)
	}
	return _unfoldStateDetail_name[_unfoldStateDetail_index[i]:_unfoldStateDetail_index[i+1]]
}
