// Code generated by "stringer -type=unfoldState"; DO NOT EDIT

package gotype

import "fmt"

const _unfoldState_name = "unfoldInvalidStateunfoldStartStateunfoldArrayStateunfoldMapStateunfoldStructStateunfoldAssignState"

var _unfoldState_index = [...]uint8{0, 18, 34, 50, 64, 81, 98}

func (i unfoldState) String() string {
	if i >= unfoldState(len(_unfoldState_index)-1) {
		return fmt.Sprintf("unfoldState(%d)", i)
	}
	return _unfoldState_name[_unfoldState_index[i]:_unfoldState_index[i+1]]
}
